# Generated by Django 3.0 on 2020-01-15 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False, verbose_name='Замовлено?')),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата замовлення')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики користувачів',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': '#Хештеги',
                'verbose_name_plural': '#Хештеги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Зображення')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.FloatField(verbose_name='Ціна')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='Ціна з урахуванням знижки')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Створено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mixture.Category', verbose_name='Категорія')),
                ('hashtag', models.ManyToManyField(to='mixture.Hashtag', verbose_name='#Хештеги')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False, verbose_name='Статус')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='mixture.Cart', verbose_name='Кошик №')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mixture.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт в заказі',
                'verbose_name_plural': 'Продукти в заказі',
            },
        ),
    ]
